#ifndef __MathPlotConfig__
#define __MathPlotConfig__

/**
@file
Subclass of MathPlotConfigDialogBuilder, which is generated by wxFormBuilder.
*/

#include "MathPlotConfigBuilder.h"

//// end generated include

#include <wx/colordlg.h>
#include <wx/fontdlg.h>
#include <wx/valnum.h>
#include <wx/fileconf.h>
#include "mathplot.h"

#ifdef ENABLE_MP_NAMESPACE
  namespace MathPlot {
#endif // ENABLE_MP_NAMESPACE

class WXDLLIMPEXP_MATHPLOT mpWindow;
class WXDLLIMPEXP_MATHPLOT mpLayer;
class WXDLLIMPEXP_MATHPLOT mpFunction;
class WXDLLIMPEXP_MATHPLOT mpLine;
class WXDLLIMPEXP_MATHPLOT mpInfoCoords;
class WXDLLIMPEXP_MATHPLOT mpInfoLegend;
class WXDLLIMPEXP_MATHPLOT mpScale;
class WXDLLIMPEXP_MATHPLOT mpText;

/**
 * Helper class to save/restore configuration
 */
class MathPlotConfigSettings : public wxFileConfig
{
  public:
    MathPlotConfigSettings(const wxString& localFilename) :
        wxFileConfig(wxEmptyString, wxEmptyString, localFilename) {}
    virtual ~MathPlotConfigSettings() {}

    void SetSettings(wxWindow* win);
    void GetSettings(wxWindow* win);
  protected:
    void DoPosition(bool set, wxWindow *win);
    void DoRecursiveSearch(bool set, wxWindow *win, const wxString &path = wxEmptyString, int level = 0);
};

/**
 * The list of index of the page of the config window
 */
typedef enum __ConfigPageIndex
{
  mpcpiNone = -1,
  mpcpiGeneral = 0,
  mpcpiLegend,
  mpcpiAxis,
  mpcpiSeries,
  mpcpiLines
} mpConfigPageId;

/** Implementing MathPlotConfigDialogBuilder */
class MathPlotConfigDialog : public MathPlotConfigDialogBuilder
{
	protected:
		// Handlers for MathPlotConfigDialogBuilder events.
		void OnnbConfigPageChanged( wxNotebookEvent& event );
		void OnbFontClick( wxCommandEvent& event );
		void OnbColorClick( wxCommandEvent& event );
		void OnAxisSelect( wxCommandEvent& event );
		void OnbAddAxisClick( wxCommandEvent& event );
		void OnbDelAxisClick( wxCommandEvent& event );
		void OncbAutoScaleClick( wxCommandEvent& event );
		void OncbFormatSelect( wxCommandEvent& event );
		void OnChoiceSeries( wxCommandEvent& event );
		void OnbDelSeriesClick( wxCommandEvent& event );
		void OnChoiceLinesSelect( wxCommandEvent& event );
		void OnbAddLinesClick( wxCommandEvent& event );
		void OnbDelLinesClick( wxCommandEvent& event );
		void OnbApplyClick( wxCommandEvent& event );
		void OnQuit( wxCommandEvent& event );
	public:
		/** Constructor */
		MathPlotConfigDialog( wxWindow* parent );
	//// end generated class members

    virtual ~MathPlotConfigDialog();

    void Initialize(mpConfigPageId id = mpcpiNone);
    void SelectChoiceSerie(unsigned int serie);
    void CreateSettingsFile(const wxString& filename, const wxString& path = wxEmptyString, bool apply = false);
    void ApplySettings(void);
    /**
     * Give access to m_settings if we want to save some others parameters
     */
    MathPlotConfigSettings* GetSettingsHandle(void)
    {
      return m_settings;
    }

  private:

    mpWindow* m_plot;
    MathPlotConfigSettings* m_settings;
    wxButton* colourButton;
    mpText* CurrentTitle;
    mpInfoLegend* CurrentLegend;
    mpInfoCoords* CurrentCoords;
    mpScale* CurrentScale;
    mpFunction* CurrentSerie;
    mpLine* CurrentLine;
    wxChoice* CurrentChoice;
    bool fontTitleChanged;
    bool fontLegendChanged;
    bool fontAxisChanged;
    // Margin validator
    unsigned int int_top, int_bottom, int_left, int_right, int_extra;
    int scale_offset;
    // Scale validator
    double scale_min, scale_max;
    // Line position validator
    double line_value;
    bool CheckBar;
    bool SerieVisibleChange;

    void Apply(int pageIndex, bool updateFont = false);
    void UpdateSelectedSerie(void);
    void UpdateSelectedLine(void);
    void UpdateAxis(void);
    void FillYAxisList(wxChoice* yChoice, bool clearChoice = true);

    void DoButtonColour(wxButton* button, const wxColour& colour);
    void DoApplyColour(const wxColour& colour);
    void UpdateFont(mpLayer* layer, wxButton* button, bool get_set);
    void SetFontChildren(wxButton* p, const wxFontData& fontdata);

    wxBrushStyle IdToBrushStyle(int id);
    int BrushStyleToId(wxBrushStyle style);

};

#ifdef ENABLE_MP_NAMESPACE
  }  // namespace MathPlot
#endif // ENABLE_MP_NAMESPACE

#endif // __MathPlotConfig__
